### ISSUE TITLE
Make the plugin MU accessible

### ISSUE THREAD

**Issue by johnie** [johnie/talandewebb#5]

**Comment by frozzare** [comment]
Since you don't do anything with plugins url and plugins dir you don't need to do anything :smile:

**Comment by johnie** [comment]
Thanks for the heads up! :+1:

## 

Johnie Hjelm / Software Engineer
Phone: +46735127321 (tel:%2B46735127321)
@johniehjelm (http://twitter.com/johniehjelm)
